workflows:
  macos-build:
    name: macOS Build
    max_build_duration: 120
    working_directory: src
    environment:
      flutter: 3.41.4
      xcode: 16.2
      cocoapods: default
    scripts:
      - name: Enable macOS desktop
        script: flutter config --enable-macos-desktop
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build macOS app
        script: flutter build macos --release
    artifacts:
      - build/macos/Build/Products/Release/*.app
      - build/macos/Build/Products/Release/*.zip

  ios-build:
    name: iOS Build (no-codesign)
    max_build_duration: 120
    working_directory: src
    environment:
      flutter: 3.41.4
      xcode: 16.2
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS (no signing)
        script: flutter build ios --release --no-codesign
      - name: Crea IPA non firmato
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r VoliDiCarta_nosign.ipa Payload
    artifacts:
      - build/ios/iphoneos/VoliDiCarta_nosign.ipa
